services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: laravel
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - psysh_config:/var/www/.config/psysh
    user: "1000:1000"
    networks:
      - laravel_network
    restart: unless-stopped 

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: test_devs_uefs
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test_devs_uefs
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    restart: unless-stopped  
    command: --default-authentication-plugin=mysql_native_password  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network
    restart: unless-stopped  

volumes:
  mysql_data:
  mysql_test_data:
  psysh_config:

networks:
  laravel_network: